name: Generate terraform docs
on: [push]

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: main

    - name: Render terraform docs inside the README.md and push changes back to PR branch
      uses: terraform-docs/gh-actions@main
      with:
        working-dir: .
        config-file: .terraform-docs.yml
        output-file: README.md
        output-method: inject
        template: |-
          <!-- BEGIN_TF_DOCS -->
          {{ .Content }}
          <!-- END_TF_DOCS --> 
        indention: 3
        git-push: true
        git-commit-message: "terraform-docs: automated action"
